### ISSUE TITLE
Lighthouse comments that are made in conjunction with another action are lost

### ISSUE THREAD

**Issue by irfanpirbhai** [Rigor/lighthouse_export#2]
Upon running export_script.rb, I'm noticing that I'm losing Lighthouse comments that were made in conjunction with another action (e.g. Changing Assigned User, Changing Tags, Changing ticket State). The actions themselves are converted into 'history' items, but the associated comments are lost. When adding attachments+commenting, however, the comments are preserved. 

Here's the (scrubbed) JSON from Lighthouse ticket export:

<pre><code>
{
  "ticket": {
    "assigned_user_id": 000002,
    "attachments_count": 5,
    "body": "Serious issue!",
    "body_html": "<div><p>Serious issue!</p></div>",
    "closed": false,
    "created_at": "2014-01-11T23:42:52Z",
    "creator_id": 000001,
    "importance": 0,
    "milestone_due_on": null,
    "milestone_id": null,
    "milestone_order": 9999,
    "number": 1,
    "permalink": "app-crashes-on-open",
    "project_id": 116319,
    "raw_data": null,
    "spam": false,
    "state": "open",
    "tag": "build10 crash newtag",
    "title": "App crashes on open",
    "updated_at": "2014-01-11T23:46:00Z",
    "user_id": 000001,
    "version": 5,
    "watchers_ids": [
      000001,
      000002
    ],
    "user_name": "Irfan Pirbhai",
    "creator_name": "Irfan Pirbhai",
    "assigned_user_name": "John Doe",
    "url": "http://test.lighthouseapp.com/projects/12345/tickets/1",
    "priority": 9999,
    "original_body": "Serious issue!",
    "latest_body": "Serious issue!",
    "original_body_html": "<div><p>Serious issue!</p></div>",
    "state_color": "aaa",
    "versions": [
      {
        "assigned_user_id": 000001,
        "attachments_count": 0,
        "body": "Serious issue!",
        "body_html": "<div><p>Serious issue!</p></div>",
        "closed": false,
        "created_at": "2014-01-11T23:42:52Z",
        "creator_id": 000001,
        "diffable_attributes": {},
        "importance": 0,
        "milestone_id": null,
        "milestone_order": 9999,
        "number": 1,
        "permalink": "app-crashes-on-open",
        "project_id": 116319,
        "spam": false,
        "state": "new",
        "tag": "build10 crash",
        "title": "App crashes on open",
        "updated_at": "2014-01-11T23:42:54Z",
        "user_id": 000001,
        "version": 1,
        "watchers_ids": [
          000001,
          000002
        ],
        "user_name": "Irfan Pirbhai",
        "creator_name": "Irfan Pirbhai",
        "assigned_user_name": "Irfan Pirbhai",
        "url": "http://test.lighthouseapp.com/projects/12345/tickets/1",
        "priority": 9999,
        "state_color": "f17"
      },
      {
        "assigned_user_id": 000001,
        "attachments_count": 0,
        "body": "Adding an attachment.",
        "body_html": "<div><p>Adding an attachment.</p></div>",
        "closed": false,
        "created_at": "2014-01-11T23:44:07Z",
        "creator_id": 000001,
        "diffable_attributes": {},
        "importance": 0,
        "milestone_id": null,
        "milestone_order": 9999,
        "number": 1,
        "permalink": "app-crashes-on-open",
        "project_id": 116319,
        "spam": false,
        "state": "new",
        "tag": "build10 crash",
        "title": "App crashes on open",
        "updated_at": "2014-01-11T23:44:09Z",
        "user_id": 000001,
        "version": 2,
        "watchers_ids": [
          000001,
          000002
        ],
        "user_name": "Irfan Pirbhai",
        "creator_name": "Irfan Pirbhai",
        "assigned_user_name": "Irfan Pirbhai",
        "url": "http://test.lighthouseapp.com/projects/12345/tickets/1",
        "priority": 9999,
        "state_color": "f17"
      },
      {
        "assigned_user_id": 000001,
        "attachments_count": 5,
        "body": "Adding some tags.",
        "body_html": "<div><p>Adding some tags.</p></div>",
        "closed": false,
        "created_at": "2014-01-11T23:44:27Z",
        "creator_id": 000001,
        "diffable_attributes": {
          "tag": "build10 crash"
        },
        "importance": 0,
        "milestone_id": null,
        "milestone_order": 9999,
        "number": 1,
        "permalink": "app-crashes-on-open",
        "project_id": 116319,
        "spam": false,
        "state": "new",
        "tag": "build10 crash newtag",
        "title": "App crashes on open",
        "updated_at": "2014-01-11T23:44:28Z",
        "user_id": 000001,
        "version": 3,
        "watchers_ids": [
          000001,
          000002
        ],
        "user_name": "Irfan Pirbhai",
        "creator_name": "Irfan Pirbhai",
        "assigned_user_name": "Irfan Pirbhai",
        "url": "http://test.lighthouseapp.com/projects/12345/tickets/1",
        "priority": 9999,
        "state_color": "f17"
      },
      {
        "assigned_user_id": 000001,
        "attachments_count": 5,
        "body": "Changing ticket state.",
        "body_html": "<div><p>Changing ticket state.</p></div>",
        "closed": false,
        "created_at": "2014-01-11T23:45:28Z",
        "creator_id": 000001,
        "diffable_attributes": {
          "state": "new"
        },
        "importance": 0,
        "milestone_id": null,
        "milestone_order": 9999,
        "number": 1,
        "permalink": "app-crashes-on-open",
        "project_id": 116319,
        "spam": false,
        "state": "open",
        "tag": "build10 crash newtag",
        "title": "App crashes on open",
        "updated_at": "2014-01-11T23:45:28Z",
        "user_id": 000001,
        "version": 4,
        "watchers_ids": [
          000001,
          000002
        ],
        "user_name": "Irfan Pirbhai",
        "creator_name": "Irfan Pirbhai",
        "assigned_user_name": "Irfan Pirbhai",
        "url": "http://test.lighthouseapp.com/projects/12345/tickets/1",
        "priority": 9999,
        "state_color": "aaa"
      },
      {
        "assigned_user_id": 000002,
        "attachments_count": 5,
        "body": "Changing assigned user.",
        "body_html": "<div><p>Changing assigned user.</p></div>",
        "closed": false,
        "created_at": "2014-01-11T23:45:59Z",
        "creator_id": 000001,
        "diffable_attributes": {
          "assigned_user": 000001
        },
        "importance": 0,
        "milestone_id": null,
        "milestone_order": 9999,
        "number": 1,
        "permalink": "app-crashes-on-open",
        "project_id": 116319,
        "spam": false,
        "state": "open",
        "tag": "build10 crash newtag",
        "title": "App crashes on open",
        "updated_at": "2014-01-11T23:46:00Z",
        "user_id": 000001,
        "version": 5,
        "watchers_ids": [
          000001,
          000002
        ],
        "user_name": "Irfan Pirbhai",
        "creator_name": "Irfan Pirbhai",
        "assigned_user_name": "John Doe",
        "url": "http://test.lighthouseapp.com/projects/12345/tickets/1",
        "priority": 9999,
        "state_color": "aaa"
      }
    ],
    "attachments": [
      {
        "image": {
          "code": "9a4a5ccd6c2f5a4b67044382fcbd9d11d5c9a6b7",
          "content_type": "image/gif",
          "created_at": "2014-01-11T23:44:08Z",
          "filename": "tumblr_m8kl6a7kpf1rwu9euo1_400.gif",
          "height": 300,
          "id": 4542299,
          "project_id": 116319,
          "size": 936054,
          "uploader_id": 000001,
          "width": 400,
          "url": "http://test.lighthouseapp.com/attachments/12345/tumblr_m8kl6a7kpf1rwu9euo1_400.gif"
        }
      }
    ]
  }
}

</code></pre>

And here is the converted (scrubbed) JSON:

<pre><code>
{
    "projects": [
    {
        "name": "Test App",
        "key": "TSTP",
        "url": "",
        "description": "This is my test App",
        "issues": [
        {
            "priority": "Trivial",
            "description": "Serious issue!",
            "status": "In Progress",
            "resolution": null,
            "reporter": "irfan.pirbhai",
            "issueType": "Bug",
            "created": "2014-01-11T23:42:52Z",
            "updated": "2014-01-11T23:46:00Z",
            "summary": "App crashes on open",
            "assignee": "john.doe",
            "externalId": 1,
            "labels": [
            "build10 crash newtag"
            ],
            "comments": [
            {
                "body": "Adding an attachment.",
                "author": "irfan.pirbhai",
                "created": "2014-01-11T23:44:07Z"
            }
            ],
            "history": [
            {
                "author": "irfan.pirbhai",
                "created": "2014-01-11T23:45:28Z",
                "items": [
                {
                    "fieldType": "jira",
                    "field": "status",
                    "from": "1",
                    "fromString": "Open",
                    "to": "3",
                    "toString": "In Progress"
                }
                ]
            },
            {
                "author": "irfan.pirbhai",
                "created": "2014-01-11T23:45:59Z",
                "items": [
                {
                    "fieldType": "jira",
                    "field": "assignee",
                    "from": "irfan.pirbhai",
                    "fromString": "irfan.pirbhai",
                    "to": "john.doe",
                    "toString": "john.doe"
                }
                ]
            }
            ],
            "attachments": [
            {
                "name": "tumblr_m8kl6a7kpf1rwu9euo1_400.gif",
                "attacher": "irfan.pirbhai",
                "created": "2014-01-11T23:44:08Z",
                "uri": "https://test-jira-migration.s3.amazonaws.com/tumblr_m8kl6a7kpf1rwu9euo1_400.gif",
                "description": "original lighthouse url: http://test.lighthouseapp.com/attachments/12345/tumblr_m8kl6a7kpf1rwu9euo1_400.gif"
            }
            ]
        }
        ]
    }
    ]
}
</code></pre>

You'll notice that, although there were originally comments with each of the 4 actions, only one persisted.

**Comment by wcmonty** [comment]
Closing as this isn't maintained.
